# 第一步 收集数据

https://grouplens.org/datasets/movielens/

# 第二步 准备数据

In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [2]:
ratings_df = pd.read_csv('ml-latest-small/ratings.csv')
ratings_df.tail()

userId  movieId  rating   timestamp
100831     610   166534     4.0  1493848402
100832     610   168248     5.0  1493850091
100833     610   168250     5.0  1494273047
100834     610   168252     5.0  1493846352
100835     610   170875     3.0  1493846415

In [3]:
movies_df = pd.read_csv('ml-latest-small/movies.csv')
movies_df.tail()

movieId                                      title  \
9737   193581  Black Butler: Book of the Atlantic (2017)   
9738   193583               No Game No Life: Zero (2017)   
9739   193585                               Flint (2017)   
9740   193587        Bungo Stray Dogs: Dead Apple (2018)   
9741   193609        Andrew Dice Clay: Dice Rules (1991)   

                               genres  
9737  Action|Animation|Comedy|Fantasy  
9738         Animation|Comedy|Fantasy  
9739                            Drama  
9740                 Action|Animation  
9741                           Comedy

In [4]:
movies_df['movieRow'] = movies_df.index
movies_df.tail()

movieId                                      title  \
9737   193581  Black Butler: Book of the Atlantic (2017)   
9738   193583               No Game No Life: Zero (2017)   
9739   193585                               Flint (2017)   
9740   193587        Bungo Stray Dogs: Dead Apple (2018)   
9741   193609        Andrew Dice Clay: Dice Rules (1991)   

                               genres  movieRow  
9737  Action|Animation|Comedy|Fantasy      9737  
9738         Animation|Comedy|Fantasy      9738  
9739                            Drama      9739  
9740                 Action|Animation      9740  
9741                           Comedy      9741

## 筛选 movies_df 中的特征

In [5]:
movies_df = movies_df[['movieRow', 'movieId', 'title']]
movies_df.to_csv('ml-latest-small/moviesProcessed.csv', index=False, header=True, encoding='utf-8')

In [6]:
movies_df

movieRow  movieId                                      title
0            0        1                           Toy Story (1995)
1            1        2                             Jumanji (1995)
2            2        3                    Grumpier Old Men (1995)
3            3        4                   Waiting to Exhale (1995)
4            4        5         Father of the Bride Part II (1995)
...        ...      ...                                        ...
9737      9737   193581  Black Butler: Book of the Atlantic (2017)
9738      9738   193583               No Game No Life: Zero (2017)
9739      9739   193585                               Flint (2017)
9740      9740   193587        Bungo Stray Dogs: Dead Apple (2018)
9741      9741   193609        Andrew Dice Clay: Dice Rules (1991)

[9742 rows x 3 columns]

# 将 ratings_df 中的 movieId 替换为行号

In [7]:
ratings_df = pd.merge(ratings_df, movies_df, on='movieId')
ratings_df.head()

userId  movieId  rating   timestamp  movieRow             title
0       1        1     4.0   964982703         0  Toy Story (1995)
1       5        1     4.0   847434962         0  Toy Story (1995)
2       7        1     4.5  1106635946         0  Toy Story (1995)
3      15        1     2.5  1510577970         0  Toy Story (1995)
4      17        1     4.5  1305696483         0  Toy Story (1995)

In [8]:
ratings_df = ratings_df[['userId', 'movieRow', 'rating']]
ratings_df.to_csv('ml-latest-small/ratingsProcessed.csv', index=False, header=True, encoding='utf-8')

In [9]:
ratings_df.tail()

userId  movieRow  rating
100831     610      9325     2.5
100832     610      9330     4.5
100833     610      9342     3.0
100834     610      9389     3.5
100835     610      9390     3.5

## 创建电影评分矩阵 rating 和 评分记录矩阵 record

In [10]:
userNo = ratings_df['userId'].max() + 1
movieNo = ratings_df['movieRow'].max() + 1
print(userNo, movieNo)

611 9742


In [11]:
rating = np.zeros((movieNo, userNo))

In [12]:
flag = 0 # 记录处理进度
ratings_df_length = np.shape(ratings_df)[0] # ratings_df 样本个数
for index, row in ratings_df.iterrows():
    rating[int(row['movieRow']), int(row['userId'])] = row['rating']
    flag += 1
    if flag % 100 == 0 or flag == ratings_df_length:
        print('processed {}, {} left'.format(flag, ratings_df_length-flag))

processed 100, 100736 left
processed 200, 100636 left
processed 300, 100536 left
processed 400, 100436 left
processed 500, 100336 left
processed 600, 100236 left
processed 700, 100136 left
processed 800, 100036 left
processed 900, 99936 left
processed 1000, 99836 left
processed 1100, 99736 left
processed 1200, 99636 left
processed 1300, 99536 left
processed 1400, 99436 left
processed 1500, 99336 left
processed 1600, 99236 left
processed 1700, 99136 left
processed 1800, 99036 left
processed 1900, 98936 left
processed 2000, 98836 left
processed 2100, 98736 left
processed 2200, 98636 left
processed 2300, 98536 left
processed 2400, 98436 left
processed 2500, 98336 left
processed 2600, 98236 left
processed 2700, 98136 left
processed 2800, 98036 left
processed 2900, 97936 left
processed 3000, 97836 left
processed 3100, 97736 left
processed 3200, 97636 left
processed 3300, 97536 left
processed 3400, 97436 left
processed 3500, 97336 left
processed 3600, 97236 left
processed 3700, 97136 left
pr

processed 29800, 71036 left
processed 29900, 70936 left
processed 30000, 70836 left
processed 30100, 70736 left
processed 30200, 70636 left
processed 30300, 70536 left
processed 30400, 70436 left
processed 30500, 70336 left
processed 30600, 70236 left
processed 30700, 70136 left
processed 30800, 70036 left
processed 30900, 69936 left
processed 31000, 69836 left
processed 31100, 69736 left
processed 31200, 69636 left
processed 31300, 69536 left
processed 31400, 69436 left
processed 31500, 69336 left
processed 31600, 69236 left
processed 31700, 69136 left
processed 31800, 69036 left
processed 31900, 68936 left
processed 32000, 68836 left
processed 32100, 68736 left
processed 32200, 68636 left
processed 32300, 68536 left
processed 32400, 68436 left
processed 32500, 68336 left
processed 32600, 68236 left
processed 32700, 68136 left
processed 32800, 68036 left
processed 32900, 67936 left
processed 33000, 67836 left
processed 33100, 67736 left
processed 33200, 67636 left
processed 33300, 675

processed 59200, 41636 left
processed 59300, 41536 left
processed 59400, 41436 left
processed 59500, 41336 left
processed 59600, 41236 left
processed 59700, 41136 left
processed 59800, 41036 left
processed 59900, 40936 left
processed 60000, 40836 left
processed 60100, 40736 left
processed 60200, 40636 left
processed 60300, 40536 left
processed 60400, 40436 left
processed 60500, 40336 left
processed 60600, 40236 left
processed 60700, 40136 left
processed 60800, 40036 left
processed 60900, 39936 left
processed 61000, 39836 left
processed 61100, 39736 left
processed 61200, 39636 left
processed 61300, 39536 left
processed 61400, 39436 left
processed 61500, 39336 left
processed 61600, 39236 left
processed 61700, 39136 left
processed 61800, 39036 left
processed 61900, 38936 left
processed 62000, 38836 left
processed 62100, 38736 left
processed 62200, 38636 left
processed 62300, 38536 left
processed 62400, 38436 left
processed 62500, 38336 left
processed 62600, 38236 left
processed 62700, 381

processed 88900, 11936 left
processed 89000, 11836 left
processed 89100, 11736 left
processed 89200, 11636 left
processed 89300, 11536 left
processed 89400, 11436 left
processed 89500, 11336 left
processed 89600, 11236 left
processed 89700, 11136 left
processed 89800, 11036 left
processed 89900, 10936 left
processed 90000, 10836 left
processed 90100, 10736 left
processed 90200, 10636 left
processed 90300, 10536 left
processed 90400, 10436 left
processed 90500, 10336 left
processed 90600, 10236 left
processed 90700, 10136 left
processed 90800, 10036 left
processed 90900, 9936 left
processed 91000, 9836 left
processed 91100, 9736 left
processed 91200, 9636 left
processed 91300, 9536 left
processed 91400, 9436 left
processed 91500, 9336 left
processed 91600, 9236 left
processed 91700, 9136 left
processed 91800, 9036 left
processed 91900, 8936 left
processed 92000, 8836 left
processed 92100, 8736 left
processed 92200, 8636 left
processed 92300, 8536 left
processed 92400, 8436 left
processe

In [13]:
record = rating > 0
record = np.array(record, dtype=int)
record

array([[0, 1, 0, ..., 1, 1, 1],
       [0, 0, 0, ..., 1, 0, 0],
       [0, 1, 0, ..., 1, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

# 第三步 构建模型

In [14]:
def normalizeRatings(rating, record):
    m, n = rating.shape
    rating_mean = np.zeros((m, 1))
    rating_norm = np.zeros((m, n))
    # 对每部电影进行迭代
    for i in range(m):
        idx = record[i, :] != 0
        rating_mean[i] = np.mean(rating[i, idx])
        rating_norm[i, idx] -= rating_mean[i]
    return rating_norm, rating_mean

In [15]:
rating_norm, rating_mean = normalizeRatings(rating, record)

/Users/wuzhuguanyu/opt/anaconda3/envs/tf/lib/python3.6/site-packages/numpy/core/fromnumeric.py:2920: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/Users/wuzhuguanyu/opt/anaconda3/envs/tf/lib/python3.6/site-packages/numpy/core/_methods.py:85: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)


In [16]:
rating_norm = np.nan_to_num(rating_norm)
rating_norm

array([[ 0.        , -3.92093023,  0.        , ..., -3.92093023,
        -3.92093023, -3.92093023],
       [ 0.        ,  0.        ,  0.        , ..., -3.43181818,
         0.        ,  0.        ],
       [ 0.        , -3.25961538,  0.        , ..., -3.25961538,
         0.        ,  0.        ],
       ...,
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ]])

In [17]:
rating_mean = np.nan_to_num(rating_mean)
rating_mean

array([[3.92093023],
       [3.43181818],
       [3.25961538],
       ...,
       [3.5       ],
       [3.5       ],
       [4.        ]])

In [18]:
num_features = 10

In [19]:
X_parameters = tf.Variable(tf.random_normal([movieNo, num_features], stddev=0.35))

In [20]:
Theta_parameters = tf.Variable(tf.random_normal([userNo, num_features], stddev=0.35))

### 公式：

$$
J(X,\theta)=\frac{1}{2}\sum_{(i,j):r(i,j)=1}\left(\left(\theta^{(j)}\right)^Tx^{(i)}-y^{(i,j)}\right)^2+\frac{\lambda}{2}\sum_{i=1}^{m}\sum_{k=1}^n\left(x_k^{(i)}\right)^2+\frac{\lambda}{2}\sum_{i=1}^{m}\sum_{k=1}^n\left(\theta_k^{(j)}\right)^2
$$

In [21]:
# $\lambda$ = 1
loss = 1/2 * tf.reduce_sum(((tf.matmul(X_parameters, Theta_parameters, transpose_b=True) - rating_norm) * record) ** 2) + \
       1/2 * tf.reduce_sum(X_parameters ** 2) + \
       1/2 * tf.reduce_sum(Theta_parameters ** 2)

In [22]:
learning_rate = 1e-3
epoch = 1000
optimizer = tf.train.AdamOptimizer(learning_rate)
train = optimizer.minimize(loss)

# 第四步 训练模型

In [23]:
tf.summary.scalar('loss', loss)

<tf.Tensor 'loss:0' shape=() dtype=string>

In [24]:
# 将所有信息汇总
summaryMerged = tf.summary.merge_all()

In [25]:
filename = './movie_tensorboard/{}epoch-{}rate'.format(epoch, learning_rate)

In [26]:
writer = tf.summary.FileWriter(filename)

In [27]:
sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)

In [28]:
for i in range(epoch):
    tmp, movie_summary = sess.run([train, summaryMerged])
    writer.add_summary(movie_summary, i)
    if i % 2 == 0:
        print("Epoch {} down.".format(i))

Epoch 0 down.
Epoch 2 down.
Epoch 4 down.
Epoch 6 down.
Epoch 8 down.
Epoch 10 down.
Epoch 12 down.
Epoch 14 down.
Epoch 16 down.
Epoch 18 down.
Epoch 20 down.
Epoch 22 down.
Epoch 24 down.
Epoch 26 down.
Epoch 28 down.
Epoch 30 down.
Epoch 32 down.
Epoch 34 down.
Epoch 36 down.
Epoch 38 down.
Epoch 40 down.
Epoch 42 down.
Epoch 44 down.
Epoch 46 down.
Epoch 48 down.
Epoch 50 down.
Epoch 52 down.
Epoch 54 down.
Epoch 56 down.
Epoch 58 down.
Epoch 60 down.
Epoch 62 down.
Epoch 64 down.
Epoch 66 down.
Epoch 68 down.
Epoch 70 down.
Epoch 72 down.
Epoch 74 down.
Epoch 76 down.
Epoch 78 down.
Epoch 80 down.
Epoch 82 down.
Epoch 84 down.
Epoch 86 down.
Epoch 88 down.
Epoch 90 down.
Epoch 92 down.
Epoch 94 down.
Epoch 96 down.
Epoch 98 down.
Epoch 100 down.
Epoch 102 down.
Epoch 104 down.
Epoch 106 down.
Epoch 108 down.
Epoch 110 down.
Epoch 112 down.
Epoch 114 down.
Epoch 116 down.
Epoch 118 down.
Epoch 120 down.
Epoch 122 down.
Epoch 124 down.
Epoch 126 down.
Epoch 128 down.
Epoch 130 down.

# 第五步 评估模型

In [29]:
Current_X_parameters, Current_Theta_parameters = sess.run([X_parameters, Theta_parameters])

In [30]:
predicts = np.dot(Current_X_parameters, Current_Theta_parameters.T) + rating_mean
errors = np.sqrt(np.sum((predicts - rating) ** 2))

In [31]:
print(errors)

2618.4543363537805


# 第六步 构建完整的电影推荐系统

In [32]:
user_id = input('请输入您的用户编号：')

sortedResult = predicts[:, int(user_id)].argsort()[::-1] # 从大到小排序

idx = 0
print('为您推荐20部电影：'.center(80, '='))
for i in sortedResult:
    print('%2d. 评分：%.2f，电影名：%s' % (idx + 1, predicts[i, int(user_id)], movies_df.iloc[i]['title']))
    idx += 1
    if idx == 20:
        break

请输入您的用户编号：67
===================================为您推荐20部电影：===================================
 1. 评分：3.50，电影名：My Left Eye Sees Ghosts (Ngo joh aan gin diy gwai) (2002)
 2. 评分：3.43，电影名：Tickling Giants (2017)
 3. 评分：3.42，电影名：Bone Man, The (Der Knochenmann) (2009)
 4. 评分：3.40，电影名：Too Funny to Fail: The Life and Death of The Dana Carvey Show (2017)
 5. 评分：3.39，电影名：Goodbye Charlie (1964)
 6. 评分：3.36，电影名：Ghost Graduation (2012)
 7. 评分：3.34，电影名：Saving Santa (2013)
 8. 评分：3.33，电影名：Miss Nobody (2010)
 9. 评分：3.29，电影名：Happy Feet Two (2011)
10. 评分：3.28，电影名：The Night Is Short, Walk on Girl (2017)
11. 评分：3.28，电影名：L.A. Slasher (2015)
12. 评分：3.28，电影名：Ice Age: The Great Egg-Scapade (2016)
13. 评分：3.27，电影名：Tom and Jerry: A Nutcracker Tale (2007)
14. 评分：3.27，电影名：Tales of Manhattan (1942)
15. 评分：3.26，电影名：Bloodsucking Bastards (2015)
16. 评分：3.26，电影名：What Happened Was... (1994)
17. 评分：3.24，电影名：Boy Eats Girl (2005)
18. 评分：3.24，电影名：Sun Alley (Sonnenallee) (1999)
19. 评分：3.23，电影名：Girls About Town (1931)
20. 评分：3

In [36]:
pd_predicts = pd.DataFrame(predicts)
pd_predicts.to_csv('./model/{}epoch-{}rate.csv'.format(epoch, learning_rate), index=None)

In [35]:
predicts

array([[ 3.91995238, -0.01722733, -0.11582151, ...,  0.25986942,
        -0.1304566 , -0.06802193],
       [ 3.43716086, -0.09722311,  0.10187429, ..., -0.08923179,
        -0.08980877, -0.01956064],
       [ 3.25301542,  0.03021403, -0.39298681, ...,  0.12517258,
        -0.18987302,  0.34591743],
       ...,
       [ 3.50568258,  2.07465744,  2.58316082, ...,  2.1185503 ,
         2.59294713,  1.7061975 ],
       [ 3.50176762,  1.97527635,  2.62143975, ...,  2.28221989,
         2.48156714,  1.70621991],
       [ 3.99610314,  0.88124347,  1.03100443, ...,  1.31038141,
         1.32486749,  0.72440171]])